var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/maintenance-status/route.js")
R.c("server/chunks/apps_web_src_app_api_maintenance-status_route_ts_10dlpfk._.js")
R.c("server/chunks/0llv_next_0eiezr-._.js")
R.c("server/chunks/0sj1_@opentelemetry_api_build_esm_0zw2uwe._.js")
R.c("server/chunks/1erm_@supabase_auth-js_dist_module_1bezl1i._.js")
R.c("server/chunks/node_modules__pnpm_0gi743d._.js")
R.c("server/chunks/[root-of-the-server]__0ghp4ib._.js")
R.c("server/chunks/apps_web__next-internal_server_app_api_maintenance-status_route_actions_1nlkezq.js")
R.m("[project]/node_modules/.pnpm/next@16.2.10_@babel+core@7.29.7_@opentelemetry+api@1.9.1_react-dom@19.2.7_react@19.2.7__react@19.2.7/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/apps/web/src/app/api/maintenance-status/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/.pnpm/next@16.2.10_@babel+core@7.29.7_@opentelemetry+api@1.9.1_react-dom@19.2.7_react@19.2.7__react@19.2.7/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/apps/web/src/app/api/maintenance-status/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
