-- ============================================================
-- seeds/coffee_content.sql — ELIMINADO
-- ============================================================
-- Este archivo contenía contenido de ejemplo del vertical café.
-- Se eliminó al generalizar el CMS. El seed base neutro vive en
-- 01_config.sql y 02_content.sql.
