-- ============================================================
-- seeds/nav_backup_before_migration.sql — ELIMINADO
-- ============================================================
-- Backup histórico de la navegación hardcodeada (pre-migración 12).
-- Ya no aplica; el nav base vive en 01_config.sql.
